"""
CAM Generator — Credit Appraisal Memo (Word Document Format)
Generates a professional banking-grade CAM document using python-docx.
"""
import os
from datetime import datetime
from typing import Dict, Any, List
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
import config


class CAMGenerator:
    """Generates Credit Appraisal Memo in Word document format."""

    def generate(self, decision_data: Dict[str, Any],
                 financials: Dict = None,
                 gst_data: Dict = None,
                 cibil_data: Dict = None,
                 research_findings: List[Dict] = None,
                 officer_notes: List[Dict] = None,
                 flags: List[Dict] = None) -> str:
        """
        Generate a complete CAM document.

        Returns:
            Path to the generated .docx file
        """
        doc = Document()

        # ── Page Setup ──
        section = doc.sections[0]
        section.page_width = Inches(8.5)
        section.page_height = Inches(11)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)

        # ── Title Page ──
        self._add_title_page(doc, decision_data)

        # ── Executive Summary ──
        self._add_executive_summary(doc, decision_data)

        # ── Company Overview ──
        self._add_company_overview(doc, decision_data, financials)

        # ── Financial Analysis ──
        self._add_financial_analysis(doc, financials)

        # ── GST Analysis ──
        if gst_data:
            self._add_gst_analysis(doc, gst_data)

        # ── CIBIL Analysis ──
        if cibil_data:
            self._add_cibil_analysis(doc, cibil_data)

        # ── Five Cs Assessment ──
        self._add_five_cs_assessment(doc, decision_data, flags)

        # ── Flag Summary ──
        self._add_flag_summary(doc, flags)

        # ── Research Findings ──
        if research_findings:
            self._add_research_findings(doc, research_findings)

        # ── Credit Officer Notes ──
        if officer_notes:
            self._add_officer_notes(doc, officer_notes)

        # ── SHAP Explainability ──
        self._add_shap_analysis(doc, decision_data)

        # ── Recommendation ──
        self._add_recommendation(doc, decision_data)

        # ── Save ──
        entity_id = decision_data.get("entity_id", "unknown")
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"CAM_{entity_id}_{timestamp}.docx"
        filepath = os.path.join(config.REPORTS_DIR, filename)
        os.makedirs(config.REPORTS_DIR, exist_ok=True)
        doc.save(filepath)

        return filepath

    def _add_title_page(self, doc: Document, data: Dict):
        """Add professional title page."""
        # Add spacing
        for _ in range(4):
            doc.add_paragraph("")

        title = doc.add_paragraph()
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = title.add_run("CREDIT APPRAISAL MEMORANDUM")
        run.font.size = Pt(28)
        run.font.bold = True
        run.font.color.rgb = RGBColor(0, 51, 102)

        # Subtitle
        subtitle = doc.add_paragraph()
        subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = subtitle.add_run("CONFIDENTIAL — FOR INTERNAL USE ONLY")
        run.font.size = Pt(12)
        run.font.color.rgb = RGBColor(139, 0, 0)
        run.font.italic = True

        doc.add_paragraph("")

        # Company name
        company = doc.add_paragraph()
        company.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = company.add_run(data.get("company_name", data.get("entity_id", "N/A")))
        run.font.size = Pt(22)
        run.font.bold = True

        doc.add_paragraph("")

        # Decision badge
        decision = data.get("decision", "PENDING")
        decision_para = doc.add_paragraph()
        decision_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = decision_para.add_run(f"RECOMMENDATION: {decision}")
        run.font.size = Pt(16)
        run.font.bold = True
        if decision == "APPROVED":
            run.font.color.rgb = RGBColor(0, 128, 0)
        elif decision == "REJECTED":
            run.font.color.rgb = RGBColor(178, 34, 34)
        else:
            run.font.color.rgb = RGBColor(205, 133, 0)

        doc.add_paragraph("")

        # Date
        date_para = doc.add_paragraph()
        date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = date_para.add_run(f"Date: {datetime.now().strftime('%d %B %Y')}")
        run.font.size = Pt(12)

        # Generated by
        gen = doc.add_paragraph()
        gen.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = gen.add_run("Generated by Intelli-Credit AI Engine")
        run.font.size = Pt(10)
        run.font.italic = True
        run.font.color.rgb = RGBColor(100, 100, 100)

        doc.add_page_break()

    def _add_executive_summary(self, doc: Document, data: Dict):
        """Add executive summary section."""
        doc.add_heading("1. Executive Summary", level=1)

        decision = data.get("decision", "PENDING")
        risk_score = data.get("risk_score", 50)
        loan_amount = data.get("recommended_loan_amount", 0)
        interest_rate = data.get("recommended_interest_rate", 0)
        confidence = data.get("confidence", 0)

        summary_text = (
            f"This Credit Appraisal Memorandum presents the assessment of "
            f"{data.get('company_name', 'the applicant')} for credit facility. "
            f"Based on comprehensive analysis of financial statements, GST filings, "
            f"CIBIL report, secondary research, and primary due diligence, the "
            f"Intelli-Credit AI Engine recommends: {decision}."
        )
        doc.add_paragraph(summary_text)

        # Key metrics table
        table = doc.add_table(rows=5, cols=2)
        table.style = "Light Grid Accent 1"

        cells = [
            ("Decision", decision),
            ("Risk Score", f"{risk_score:.1f} / 100"),
            ("Confidence", f"{confidence:.1%}"),
            ("Recommended Loan Amount", f"₹{loan_amount:,.0f}" if loan_amount > 0 else "N/A"),
            ("Recommended Interest Rate", f"{interest_rate:.2f}%" if interest_rate > 0 else "N/A"),
        ]

        for i, (label, value) in enumerate(cells):
            table.rows[i].cells[0].text = label
            table.rows[i].cells[1].text = str(value)
            # Bold labels
            for paragraph in table.rows[i].cells[0].paragraphs:
                for run in paragraph.runs:
                    run.font.bold = True

        doc.add_paragraph("")

        # Decision reasons
        reasons = data.get("decision_reasons", [])
        if reasons:
            doc.add_heading("Key Decision Factors", level=2)
            for reason in reasons:
                doc.add_paragraph(reason, style="List Bullet")

    def _add_company_overview(self, doc: Document, data: Dict, financials: Dict):
        """Add company overview section."""
        doc.add_heading("2. Company Overview", level=1)

        if financials:
            table = doc.add_table(rows=4, cols=2)
            table.style = "Light Grid Accent 1"
            info = [
                ("Entity ID", data.get("entity_id", "N/A")),
                ("Company Name", data.get("company_name", "N/A")),
                ("Revenue (Latest)", f"₹{float(financials.get('revenue', 0)):,.0f}"),
                ("Total Assets", f"₹{float(financials.get('total_assets', 0)):,.0f}"),
            ]
            for i, (label, value) in enumerate(info):
                table.rows[i].cells[0].text = label
                table.rows[i].cells[1].text = str(value)
                for paragraph in table.rows[i].cells[0].paragraphs:
                    for run in paragraph.runs:
                        run.font.bold = True
        else:
            doc.add_paragraph("Financial details not available.")

    def _add_financial_analysis(self, doc: Document, financials: Dict):
        """Add detailed financial analysis."""
        doc.add_heading("3. Financial Analysis", level=1)

        if not financials:
            doc.add_paragraph("No financial data available for analysis.")
            return

        doc.add_heading("Key Financial Metrics", level=2)

        revenue = float(financials.get("revenue", 0))
        ebitda = float(financials.get("ebitda", 0))
        net_profit = float(financials.get("net_profit", 0))
        total_debt = float(financials.get("total_debt", 0))
        net_worth = float(financials.get("net_worth", 0))
        current_assets = float(financials.get("current_assets", 0))
        current_liabilities = float(financials.get("current_liabilities", 0))

        de_ratio = total_debt / net_worth if net_worth > 0 else 0
        current_ratio = current_assets / current_liabilities if current_liabilities > 0 else 0

        metrics = [
            ("Revenue", f"₹{revenue:,.0f}"),
            ("EBITDA", f"₹{ebitda:,.0f}"),
            ("Net Profit", f"₹{net_profit:,.0f}"),
            ("Total Debt", f"₹{total_debt:,.0f}"),
            ("Net Worth", f"₹{net_worth:,.0f}"),
            ("Debt/Equity Ratio", f"{de_ratio:.2f}x"),
            ("Current Ratio", f"{current_ratio:.2f}"),
            ("Operating Margin", f"{float(financials.get('operating_margin', 0)):.1f}%"),
        ]

        table = doc.add_table(rows=len(metrics), cols=2)
        table.style = "Light Grid Accent 1"
        for i, (label, value) in enumerate(metrics):
            table.rows[i].cells[0].text = label
            table.rows[i].cells[1].text = value
            for paragraph in table.rows[i].cells[0].paragraphs:
                for run in paragraph.runs:
                    run.font.bold = True

    def _add_gst_analysis(self, doc: Document, gst_data: Dict):
        """Add GST analysis section."""
        doc.add_heading("4. GST Analysis (GSTR-2A vs 3B)", level=1)

        doc.add_paragraph(
            "This section compares the self-reported GSTR-3B turnover against the "
            "supplier-reported GSTR-2A data to identify potential revenue inflation "
            "or circular trading patterns."
        )

        if isinstance(gst_data, list):
            gst_data = gst_data[0] if gst_data else {}

        gstr_3b = float(gst_data.get("gstr_3b_turnover", 0))
        gstr_2a = float(gst_data.get("gstr_2a_turnover", 0))
        mismatch = float(gst_data.get("mismatch_pct", 0))

        table = doc.add_table(rows=4, cols=2)
        table.style = "Light Grid Accent 1"
        rows = [
            ("GSTR-3B Turnover (Self-reported)", f"₹{gstr_3b:,.0f}"),
            ("GSTR-2A Turnover (Supplier-reported)", f"₹{gstr_2a:,.0f}"),
            ("Mismatch Percentage", f"{mismatch:.1f}%"),
            ("Circular Trading Risk", f"{float(gst_data.get('circular_trading_risk', 0)):.0f}/100"),
        ]
        for i, (label, value) in enumerate(rows):
            table.rows[i].cells[0].text = label
            table.rows[i].cells[1].text = value
            for paragraph in table.rows[i].cells[0].paragraphs:
                for run in paragraph.runs:
                    run.font.bold = True

    def _add_cibil_analysis(self, doc: Document, cibil_data: Dict):
        """Add CIBIL analysis section."""
        doc.add_heading("5. CIBIL Commercial Report Analysis", level=1)

        metrics = [
            ("CIBIL Score", str(cibil_data.get("cibil_score", "N/A"))),
            ("Total Credit Facilities", str(cibil_data.get("total_credit_facilities", 0))),
            ("Overdue Accounts", str(cibil_data.get("overdue_accounts", 0))),
            ("Suit Filed Accounts", str(cibil_data.get("suit_filed_accounts", 0))),
            ("DPD 30+ Accounts", str(cibil_data.get("dpd_30_plus", 0))),
            ("DPD 90+ Accounts", str(cibil_data.get("dpd_90_plus", 0))),
            ("Credit Utilization", f"{float(cibil_data.get('credit_utilization_pct', 0)):.0f}%"),
        ]

        table = doc.add_table(rows=len(metrics), cols=2)
        table.style = "Light Grid Accent 1"
        for i, (label, value) in enumerate(metrics):
            table.rows[i].cells[0].text = label
            table.rows[i].cells[1].text = value
            for paragraph in table.rows[i].cells[0].paragraphs:
                for run in paragraph.runs:
                    run.font.bold = True

    def _add_five_cs_assessment(self, doc: Document, data: Dict, flags: List[Dict]):
        """Add Five Cs of Credit assessment."""
        doc.add_heading("6. Five Cs of Credit Assessment", level=1)

        five_cs = data.get("five_cs", {})
        if isinstance(five_cs, dict):
            cs_scores = {
                "Character": five_cs.get("character", 50),
                "Capacity": five_cs.get("capacity", 50),
                "Capital": five_cs.get("capital", 50),
                "Collateral": five_cs.get("collateral", 50),
                "Conditions": five_cs.get("conditions", 50),
            }
        else:
            cs_scores = {
                "Character": getattr(five_cs, "character", 50),
                "Capacity": getattr(five_cs, "capacity", 50),
                "Capital": getattr(five_cs, "capital", 50),
                "Collateral": getattr(five_cs, "collateral", 50),
                "Conditions": getattr(five_cs, "conditions", 50),
            }

        descriptions = {
            "Character": "Promoter integrity, management track record, litigation history, market reputation",
            "Capacity": "Revenue generation, debt servicing ability, operational efficiency, GST compliance",
            "Capital": "Net worth, leverage, capital adequacy, retained earnings",
            "Collateral": "Security coverage, asset quality, tangible asset backing",
            "Conditions": "Sector outlook, regulatory environment, market conditions, officer observations",
        }

        table = doc.add_table(rows=6, cols=3)
        table.style = "Light Grid Accent 1"
        table.rows[0].cells[0].text = "Parameter"
        table.rows[0].cells[1].text = "Score (/100)"
        table.rows[0].cells[2].text = "Assessment Basis"
        for paragraph in table.rows[0].cells[0].paragraphs:
            for run in paragraph.runs:
                run.font.bold = True
        for paragraph in table.rows[0].cells[1].paragraphs:
            for run in paragraph.runs:
                run.font.bold = True
        for paragraph in table.rows[0].cells[2].paragraphs:
            for run in paragraph.runs:
                run.font.bold = True

        for i, (c, score) in enumerate(cs_scores.items()):
            row = table.rows[i + 1]
            row.cells[0].text = c
            row.cells[1].text = f"{score:.0f}"
            row.cells[2].text = descriptions.get(c, "")

    def _add_flag_summary(self, doc: Document, flags: List[Dict]):
        """Add red/green/blue flag summary."""
        doc.add_heading("7. Risk Flag Summary", level=1)

        if not flags:
            doc.add_paragraph("No flags generated.")
            return

        red_flags = [f for f in flags if f.get("color") == "red"]
        green_flags = [f for f in flags if f.get("color") == "green"]
        blue_flags = [f for f in flags if f.get("color") == "blue"]

        # Summary counts
        doc.add_paragraph(
            f"Total Flags: {len(flags)} "
            f"(Red: {len(red_flags)}, Green: {len(green_flags)}, Blue: {len(blue_flags)})"
        )

        if red_flags:
            doc.add_heading("Red Flags (High Risk)", level=2)
            for f in red_flags:
                p = doc.add_paragraph(style="List Bullet")
                run = p.add_run(f"[{f.get('category', '')}] {f.get('title', '')}")
                run.font.bold = True
                run.font.color.rgb = RGBColor(178, 34, 34)
                p.add_run(f"\n{f.get('description', '')}")
                source = f.get('source', '')
                if source:
                    run2 = p.add_run(f"\nSource: {source}")
                    run2.font.italic = True
                    run2.font.size = Pt(9)

        if blue_flags:
            doc.add_heading("Blue Flags (Monitor)", level=2)
            for f in blue_flags:
                p = doc.add_paragraph(style="List Bullet")
                run = p.add_run(f"[{f.get('category', '')}] {f.get('title', '')}")
                run.font.bold = True
                run.font.color.rgb = RGBColor(0, 0, 178)
                p.add_run(f"\n{f.get('description', '')}")

        if green_flags:
            doc.add_heading("Green Flags (Positive)", level=2)
            for f in green_flags:
                p = doc.add_paragraph(style="List Bullet")
                run = p.add_run(f"[{f.get('category', '')}] {f.get('title', '')}")
                run.font.bold = True
                run.font.color.rgb = RGBColor(0, 100, 0)
                p.add_run(f"\n{f.get('description', '')}")

    def _add_research_findings(self, doc: Document, findings: List[Dict]):
        """Add secondary research findings."""
        doc.add_heading("8. Secondary Research Findings", level=1)

        for f in findings:
            p = doc.add_paragraph(style="List Bullet")
            sentiment = f.get("sentiment", "neutral")
            icon = "[+]" if sentiment == "positive" else "[-]" if sentiment == "negative" else "[~]"
            run = p.add_run(f"{icon} {f.get('title', '')}")
            run.font.bold = True
            p.add_run(f"\n{f.get('snippet', '')}")
            source = f.get("source", "")
            if source:
                run2 = p.add_run(f"\nSource: {source}")
                run2.font.italic = True
                run2.font.size = Pt(9)

    def _add_officer_notes(self, doc: Document, notes: List[Dict]):
        """Add credit officer notes section."""
        doc.add_heading("9. Primary Due Diligence Notes", level=1)

        doc.add_paragraph(
            "The following qualitative observations were recorded by the Credit Officer "
            "during site visits and management interviews:"
        )

        for note in notes:
            p = doc.add_paragraph(style="List Bullet")
            severity = note.get("severity", "low")
            icon = {"critical": "[-]", "high": "[-]", "medium": "[~]", "low": "[+]"}.get(severity, "[~]")
            run = p.add_run(f"{icon} [{note.get('category', 'General')}] ")
            run.font.bold = True
            p.add_run(note.get("note", ""))
            run2 = p.add_run(f"\nSeverity: {severity.upper()} | Officer: {note.get('officer_name', 'N/A')}")
            run2.font.italic = True
            run2.font.size = Pt(9)

    def _add_shap_analysis(self, doc: Document, data: Dict):
        """Add SHAP explainability section."""
        doc.add_heading("10. Model Explainability (SHAP Analysis)", level=1)

        doc.add_paragraph(
            "The following table shows the contribution of each feature to the final "
            "credit decision, as computed by SHAP (SHapley Additive exPlanations). "
            "Positive values push toward APPROVAL, negative values push toward REJECTION."
        )

        shap_vals = data.get("shap_explanations", {})
        if not shap_vals:
            doc.add_paragraph("SHAP values not available.")
            return

        # Sort by absolute value
        sorted_shap = sorted(shap_vals.items(), key=lambda x: abs(x[1]), reverse=True)

        table = doc.add_table(rows=min(len(sorted_shap), 15) + 1, cols=3)
        table.style = "Light Grid Accent 1"
        table.rows[0].cells[0].text = "Feature"
        table.rows[0].cells[1].text = "SHAP Value"
        table.rows[0].cells[2].text = "Impact"
        for cell in table.rows[0].cells:
            for paragraph in cell.paragraphs:
                for run in paragraph.runs:
                    run.font.bold = True

        for i, (feature, val) in enumerate(sorted_shap[:15]):
            row = table.rows[i + 1]
            row.cells[0].text = feature
            row.cells[1].text = f"{val:+.4f}"
            if val > 0.05:
                row.cells[2].text = "[+] Supports Approval"
            elif val < -0.05:
                row.cells[2].text = "[-] Supports Rejection"
            else:
                row.cells[2].text = "[=] Neutral"

    def _add_recommendation(self, doc: Document, data: Dict):
        """Add final recommendation section."""
        doc.add_page_break()
        doc.add_heading("11. Final Recommendation", level=1)

        decision = data.get("decision", "PENDING")
        risk_score = data.get("risk_score", 50)
        loan_amount = data.get("recommended_loan_amount", 0)
        interest_rate = data.get("recommended_interest_rate", 0)

        # Decision box
        p = doc.add_paragraph()
        run = p.add_run(f"\nRECOMMENDATION: {decision}\n")
        run.font.size = Pt(18)
        run.font.bold = True
        if decision == "APPROVED":
            run.font.color.rgb = RGBColor(0, 128, 0)
        elif decision == "REJECTED":
            run.font.color.rgb = RGBColor(178, 34, 34)
        else:
            run.font.color.rgb = RGBColor(205, 133, 0)

        if decision != "REJECTED" and loan_amount > 0:
            table = doc.add_table(rows=3, cols=2)
            table.style = "Light Grid Accent 1"
            table.rows[0].cells[0].text = "Recommended Loan Amount"
            table.rows[0].cells[1].text = f"₹{loan_amount:,.0f}"
            table.rows[1].cells[0].text = "Recommended Interest Rate"
            table.rows[1].cells[1].text = f"{interest_rate:.2f}%"
            table.rows[2].cells[0].text = "Risk Score"
            table.rows[2].cells[1].text = f"{risk_score:.1f}/100"
            for row in table.rows:
                for paragraph in row.cells[0].paragraphs:
                    for run in paragraph.runs:
                        run.font.bold = True

        doc.add_paragraph("")

        # Decision narrative
        doc.add_heading("Decision Rationale", level=2)
        reasons = data.get("decision_reasons", [])
        if reasons:
            for reason in reasons:
                doc.add_paragraph(reason, style="List Bullet")
        else:
            doc.add_paragraph("No specific decision factors recorded.")

        # Disclaimer
        doc.add_paragraph("")
        disclaimer = doc.add_paragraph()
        run = disclaimer.add_run(
            "DISCLAIMER: This Credit Appraisal Memo is generated by the Intelli-Credit "
            "AI Engine using XGBoost machine learning with SHAP explainability. While the "
            "model provides data-driven recommendations, final lending decisions should be "
            "made by authorized credit officers in compliance with institutional policies "
            "and RBI guidelines."
        )
        run.font.size = Pt(8)
        run.font.italic = True
        run.font.color.rgb = RGBColor(100, 100, 100)
